#-------------------------------
# General Site Settings
title: Spicy Data
logo: logo.svg # You can add own logo.
description: Spicy Data is modern minimal blog for all things data science.


#-------------------------------
# Author Settings
author:
  name: Eddie Lalo Carrasco
  images: 01.jpg
  say-hello: Hello, I’m <strong>Eduardo Lalo Carrasco</strong>
  bio: A <strong>Mathematics</strong>, <strong>Data Scientist</strong>, <strong>Certified Ethical Hacking</strong>, and machine learning. I share tutorials, free resources and inspiration. Loves <a href="#">music</a> & being an outdoorsman.


#-------------------------------
# Contact links
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/eddielalocarrasco # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
#-------------------------------
# Comment Section (Disqus)
disqus-identifier: ronin-black # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: eddielalocarrasco # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
